name: openMail
options:
  bundleIdPrefix: nykadamec
  deploymentTarget:
    iOS: "27.0"
targets:
  openMail:
    type: application
    platform: iOS
    sources: [openMail]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nykadamec.openmail
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: openMail
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "0.0.16"
        CURRENT_PROJECT_VERSION: "16"
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
